// Shop Page
export const GET_CATEGORY_NAME = "GET_CATEGORY_NAME";
export const GET_AUTHOR_NAME = "GET_AUTHOR_NAME";
export const GET_DISPLAY_BOOK = "GET_DISPLAY_BOOK";

// Filter
export const SET_FILTER_SHOW = "SET_FILTER_SHOW";
export const SET_FILTER_SORT = "SET_FILTER_SORT";
export const FILTER_BY_AUTHOR = "FILTER_BY_AUTHOR";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_RATING = "FILTER_BY_RATING";

export const GET_PAGINATION = "GET_PAGINATION";
export const HANDLE_PAGINATE = "HANDLE_PAGINATE";
