// Shop Page
export const GET_CATEGORY_NAME = "GET_CATEGORY_NAME";
export const GET_AUTHOR_NAME = "GET_AUTHOR_NAME";
export const GET_DISPLAY_BOOK = "GET_DISPLAY_BOOK";
export const SET_DISPLAY_DEFAULT = "SET_DISPLAY_DEFAULT";

// Filter
export const SET_FILTER_SHOW = "SET_FILTER_SHOW";
export const SET_FILTER_SORT = "SET_FILTER_SORT";
export const FILTER_BY_AUTHOR = "FILTER_BY_AUTHOR";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_RATING = "FILTER_BY_RATING";

// Pagination
export const GET_PAGINATION = "GET_PAGINATION";
export const HANDLE_PAGINATE = "HANDLE_PAGINATE";

// Product Page
export const GET_DETAIL_BOOK = "GET_DETAIL_BOOK";
export const SET_FILTER_SHOW_REVIEW = "SET_FILTER_SHOW_REVIEW";
export const SET_FILTER_SORT_REVIEW = "SET_FILTER_SORT_REVIEW";

// Cart
export const SET_CART_QUANTITY = "SET_CART_QUANTITY";
